### PR TITLE
RAPIDS CuDF integration (sans tests)

### PR DESCRIPTION
**Pull request by bernease**
Adds optional import (try-block) of RAPIDS CuDF dataframe object (though not included in setup.py dependencies)

NOTE: There were a number of pending formatting changes from black unrelated to this change. I will add them if it blocks build.

### CODE REVIEW

**Comment by ibackus** [comment]
We should add a very simple test just to verify the CuDF works.

Longer term this brings out the issue that we'll need to start having tests which target optional dependencies.  This can be done pretty easily (though it's a bit hacky) by modifying `sys.modules` in a `pytest` fixture.

**Comment by bernease** [comment]
I completely agree. I was also trying to figure out how to target optional
dependencies in the test in another change but hadn't gone the sys.modules
route (or find success).

**Comment by andyndang** [comment]
> We should add a very simple test just to verify the CuDF works.

Surprisingly hard! We can do mock but actual CuDF requires enormous infra set up! 

There CI pipeline doesn't have GitHub action tests either (since the library requires CUDA, understandably): https://github.com/rapidsai/cudf/tree/branch-0.17/.github

Anyway this CR seems to require some rework as in it does not address the issue here: https://github.com/rapidsai/cudf/issues/6743

**Comment by bernease** [comment]
Replicated in #91. Closing.

**Pull request closed without merging**
