### PR TITLE
Fix deserialize timezone info and  merge of _metadata

### LINKED ISSUE #994: TypeError: can't compare offset-naive and offset-aware datetimes
## Description

```python
from whylogs.core import DatasetProfile, DatasetProfileView
import pandas as pd

df = pd.read_csv('./data.csv')

profile1 = DatasetProfile()
profile1.track(df)

ser = profile1.view().serialize()
view = DatasetProfileView.deserialize(ser)

profile2 = DatasetProfile()
profile2.track(df)
view.merge(profile2.view()) # error
```

This errors out with the following message

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    view.merge(profile2.view()) # error
  File "/home/anthony/workspace/dataflow_templates/.venv/lib/python3.8/site-packages/whylogs/core/view/dataset_profile_view.py", line 157, in merge
    dataset_timestamp=DatasetProfileView._min_datetime(self._dataset_timestamp, other.dataset_timestamp),
  File "/home/anthony/workspace/dataflow_templates/.venv/lib/python3.8/site-packages/whylogs/core/view/dataset_profile_view.py", line 94, in _min_datetime
    return a if a < b else b
TypeError: can't compare offset-naive and offset-aware datetimes
```

Older versions of whylogs (1.1.12, for example) don't do this.

### PR DESCRIPTION
**Pull request by jamie256**
## Description

Split out the post pickle deserialization bug fixes for timestamp timezone and _metdata from larger ResultSet merge changes here:
https://github.com/whylabs/whylogs/pull/996

Fixes #994 

- [x] I have reviewed the [Guidelines for Contributing](CONTRIBUTING.md) and the [Code of Conduct](CODE_OF_CONDUCT.md).

### CODE REVIEW

**Review by naddeoa — APPROVED** [review]
Test looks good to me. I can't easily test this out locally to verify though.

**Comment by naddeoa** [comment]
Actually, I couldn't confirm the fix. Made a sample repo with what I'm doing:

https://github.com/naddeoa/whylogs-bug-repgro

Should be able to just

```bash
git clone https://github.com/naddeoa/whylogs-bug-repgro
cd ./whylogs-bug-repgro
make
```

I'm using python 3.8.15 for this. You might have to do `poetry env use /path/to/python-3.8` to make it actually work.

(forgive the typo in the name but whats' done is done)

**Review by naddeoa — DISMISSED** [review]
Actually, I couldn't confirm the fix. Made a sample repo with what I'm doing:

https://github.com/naddeoa/whylogs-bug-repgro

Should be able to just

```bash
git clone https://github.com/naddeoa/whylogs-bug-repgro
cd ./whylogs-bug-repgro
make
```

I'm using python 3.8.15 for this. You might have to do `poetry env use /path/to/python-3.8` to make it actually work.

(forgive the typo in the name but what's done is done)

**Comment by naddeoa** [comment]
The newest test wheel wroks locally now

**Comment by jamie256** [comment]
> Actually, I couldn't confirm the fix. Made a sample repo with what I'm doing:
> 
> https://github.com/naddeoa/whylogs-bug-repgro
> 
> Should be able to just
> 
> ```shell
> git clone https://github.com/naddeoa/whylogs-bug-repgro
> cd ./whylogs-bug-repgro
> make
> ```
> 
> I'm using python 3.8.15 for this. You might have to do `poetry env use /path/to/python-3.8` to make it actually work.
> 
> (forgive the typo in the name but what's done is done)

I think that one is installing the wrong wheel somehow, your test looks good on these changes if I run against locally built and installed whylogs with this PR's changes. Thanks for the test!

**Review by naddeoa — APPROVED** [review]

**Pull request merged**
