### PR TITLE
Fix error due to importing MLFlow (#72 + #76)

### LINKED ISSUE #72: MLFlow NameError
When I don't have the optional MLFlow dependency installed I get the following exception the first time I try to import the `numbertracker`.  The second time I run the import, everything works just fine.

```python
from whylogs.core.statistics import numbertracker



Failed to import MLFLow
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-3964e19b3cb4> in <module>
----> 1 from whylogs.core.statistics import numbertracker

~/src/whylogs-github/src/whylogs/__init__.py in <module>
      4 from .app.session import get_or_create_session
      5 from .app.session import reset_default_session
----> 6 from .mlflow import enable_mlflow
      7 
      8 __all__ = [

~/src/whylogs-github/src/whylogs/mlflow/__init__.py in <module>
----> 1 from .patcher import enable_mlflow
      2 
      3 __all__ = ["enable_mlflow"]

~/src/whylogs-github/src/whylogs/mlflow/patcher.py in <module>
    145 
    146 _active_whylogs = []
--> 147 _original_end_run = mlflow.tracking.fluent.end_run
    148 
    149 

NameError: name 'mlflow' is not defined
```

### PR DESCRIPTION
**Pull request by andyndang**
Fix #72 and #76

### CODE REVIEW

**Review by ibackus — CHANGES_REQUESTED** [review]
Still doesn't work, but with a different error.  Import works the second time around.

```python
In [1]: from whylogs.core.statistics import numbertracker
   ...:
Failed to import MLFLow
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1-3964e19b3cb4> in <module>
----> 1 from whylogs.core.statistics import numbertracker

~/src/whylogs-github/src/whylogs/__init__.py in <module>
      4 from .app.session import get_or_create_session
      5 from .app.session import reset_default_session
----> 6 from .mlflow import enable_mlflow
      7
      8 __all__ = [

~/src/whylogs-github/src/whylogs/mlflow/__init__.py in <module>
----> 1 from .patcher import enable_mlflow
      2
      3 __all__ = ["enable_mlflow"]

~/src/whylogs-github/src/whylogs/mlflow/patcher.py in <module>
    147
    148
--> 149 def _end_run(status=RunStatus.to_string(RunStatus.FINISHED)):
    150     """Redefine when an MLRun ends by closing Whylogs."""
    151     global _active_whylogs

NameError: name 'RunStatus' is not defined
```

**Comment by andyndang** [comment]
Yeah I refer to an imported type in the type annotation. Pushing out a fix

**Review by ibackus — APPROVED** [review]
Okay, seems to work now!

**Comment by andyndang** [comment]
Pushed a change to fix #76 as well

**Pull request merged**
