### PR TITLE
README update

### PR DESCRIPTION
**Pull request by lalmei**

### CODE REVIEW

**Comment by andyndang** [comment]
Will we update the 

```
Latest release: 0.4.5
```
manually or automatically?

**Comment by andyndang** [comment]
Also everything should be `whylogs` lowercase

**Comment by lalmei** [comment]
> Will we update the
> 
> ```
> Latest release: 0.4.5
> ```
> 
> manually or automatically?

yeah right now as it stand it will be manually number and add a link to official release notes.

**Review by andyndang — APPROVED** [review]
Looking amazing!

**Pull request merged**
