### PR TITLE
WHY-1747 Support tracking a CuDF dataframe

### PR DESCRIPTION
**Pull request by andyndang**
This is caused by https://github.com/rapidsai/cudf/issues/6743

Manually tested since we don't have the infra to test with CuDF automatically

### CODE REVIEW

**Comment by ibackus** [comment]
@andyndang do you just want us to review?  If so, mark us as reviewers

If you are the owner of this PR I think you should assign yourself.  I find that workflow is good on github

**Comment by andyndang** [comment]
> @andyndang do you just want us to review? If so, mark us as reviewers

Yes 👍

**Review by ibackus — APPROVED** [review]
Seems reasonable, even if I can't test this.

**Review by bernease — APPROVED** [review]
Looks fine. Should this be paired with a change in dependencies on our end?

**Comment by andyndang** [comment]
> Looks fine. Should this be paired with a change in dependencies on our end?

No. We can't have any dependency with CUDF since it doesn't work on normal environments. They are not installable via pypi so I won't put them in any extra dependency group either

**Pull request merged**
