### PR TITLE
Select Multiple profiles for comparison in viewer

### PR DESCRIPTION
**Pull request by valer-whylabs**
### General Checklist

* [ ] Tests added for this feature/bug
      if it was a bug, test must cover it.
* [x] Conform by the style guides, by using formatter
* [ ] Documentation updated
* [x] (optional) Please add a label to your PR

### CODE REVIEW

**Comment by lalmei** [comment]
@valer-whylabs I fixed a minor conflict, if you can  pls do a quick review

**Review by lalmei — APPROVED** [review]
LGTM

**Comment by lalmei** [comment]
Did you rebase or merge ?

**Comment by valer-whylabs** [comment]
> Did you rebase or merge ?

I squashed all the commits on my branch, after that I have merged mainline into my branch and resolved all the conflicts.
It seems all checks pass now.

**Comment by lalmei** [comment]
Merged in #272

**Pull request closed without merging**
